
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProviders from "./provider";
import DashboardLayout from "@/layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E commerce",
  description: "Generated by Genpixels",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppProviders>
      <DashboardLayout>{children}</DashboardLayout>
      </AppProviders>
      </body>
    </html>
  );
}
